//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMLib.RapidPrototyping.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMLib.RapidPrototyping.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lubim Ta.
        ///Dala som hriat veceru.
        ///Este furt to sviet.
        ///Teraz to zhaslo.
        ///Tieto cukriky by som potrebovala niekam inam supnut.
        ///Non nisl in, metus proin.
        ///Ut justo, sodales proin arcu, vitae luctus mollis.
        ///Neque a laoreet, ullam bibendum.
        ///Bibendum magna, sit lectus.
        ///Ac in tortor, quisque lectus, cubilia non bibendum.
        ///Nullam enim quis, imperdiet vehicula, magna in sem.
        ///Vel congue a, habitasse tellus.
        ///Elementum feugiat velit, dictum libero.
        ///Nascetur blandit velit, quis integer..
        /// </summary>
        internal static string loremIpsum {
            get {
                return ResourceManager.GetString("loremIpsum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milan
        ///Zuzka
        ///Peter
        ///Pavol
        ///Juraj
        ///Mikuláš
        ///Michal
        ///Katka.
        /// </summary>
        internal static string slovak_first_name {
            get {
                return ResourceManager.GetString("slovak_first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobza
        ///Martiniak
        ///Petrák
        ///Gonščák
        ///Husák.
        /// </summary>
        internal static string slovak_last_name {
            get {
                return ResourceManager.GetString("slovak_last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ahoj
        ///cau
        ///nazdar
        ///radar
        ///dozor
        ///cezar
        ///random.
        /// </summary>
        internal static string slovak_words_lowercase {
            get {
                return ResourceManager.GetString("slovak_words_lowercase", resourceCulture);
            }
        }
    }
}
