//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMLib.RapidPrototyping.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMLib.RapidPrototyping.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaron
        ///Aaron
        ///Abbey
        ///Abbie
        ///Abby
        ///Abdul
        ///Abe
        ///Abel
        ///Abigail
        ///Abraham
        ///Abram
        ///Ada
        ///Adah
        ///Adalberto
        ///Adaline
        ///Adam
        ///Adam
        ///Adan
        ///Addie
        ///Adela
        ///Adelaida
        ///Adelaide
        ///Adele
        ///Adelia
        ///Adelina
        ///Adeline
        ///Adell
        ///Adella
        ///Adelle
        ///Adena
        ///Adina
        ///Adolfo
        ///Adolph
        ///Adria
        ///Adrian
        ///Adrian
        ///Adriana
        ///Adriane
        ///Adrianna
        ///Adrianne
        ///Adrien
        ///Adriene
        ///Adrienne
        ///Afton
        ///Agatha
        ///Agnes
        ///Agnus
        ///Agripina
        ///Agueda
        ///Agustin
        ///Agustina
        ///Ahmad
        ///Ahmed
        ///Ai
        ///Aida
        ///Aide
        ///Aiko
        ///Aileen
        ///Ailene
        ///Aimee
        ///Aisha
        ///Aja
        ///Akiko
        ///Akilah
        ///Al
        ///Alaina
        ///Alaine
        ///Alan
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string english_first_name {
            get {
                return ResourceManager.GetString("english_first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaberg
        ///Aaby
        ///Aadland
        ///Aagaard
        ///Aakre
        ///Aaland
        ///Aalbers
        ///Aalderink
        ///Aalund
        ///Aamodt
        ///Aamot
        ///Aanderud
        ///Aanenson
        ///Aanerud
        ///Aarant
        ///Aardema
        ///Aarestad
        ///Aarhus
        ///Aaron
        ///Aarons
        ///Aaronson
        ///Aarsvold
        ///Aas
        ///Aasby
        ///Aase
        ///Aasen
        ///Aavang
        ///Abad
        ///Abadi
        ///Abadie
        ///Abair
        ///Abaja
        ///Abajian
        ///Abalos
        ///Abaloz
        ///Abar
        ///Abarca
        ///Abare
        ///Abascal
        ///Abasta
        ///Abate
        ///Abati
        ///Abatiell
        ///Abato
        ///Abatti
        ///Abaunza
        ///Abaya
        ///Abbadessa
        ///Abbamonte
        ///Abbas
        ///Abbasi
        ///Abbassi
        ///Abbate
        ///Abbatiello
        ///Abbay
        ///Abbe
        ///Abbed
        ///Abbenante
        ///Abbey
        ///Abbinanti
        ///Abbington
        ///Abbitt
        ///Abb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string english_last_name {
            get {
                return ResourceManager.GetString("english_last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aardvark
        ///aardwolf
        ///aaron
        ///aback
        ///abacus
        ///abaft
        ///abalone
        ///abandon
        ///abandoned
        ///abandonment
        ///abandons
        ///abase
        ///abased
        ///abasement
        ///abash
        ///abashed
        ///abate
        ///abated
        ///abatement
        ///abates
        ///abattoir
        ///abattoirs
        ///abbe
        ///abbess
        ///abbey
        ///abbeys
        ///abbot
        ///abbots
        ///abbreviate
        ///abbreviated
        ///abbreviates
        ///abbreviating
        ///abbreviation
        ///abbreviations
        ///abdicate
        ///abdicated
        ///abdicates
        ///abdicating
        ///abdication
        ///abdomen
        ///abdomens
        ///abdominal
        ///abduct
        ///abducted
        ///abducting
        ///abduction
        ///abductions
        ///abductor
        ///abductors
        ///abducts
        ///abe
        ///abeam
        ///abel
        ///abe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string english_words_lowercase {
            get {
                return ResourceManager.GetString("english_words_lowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, ornare neque vehicula, sapien donec nunc, nisl sagittis.
        ///Erat mattis, nisl adipiscing, sed et lectus.
        ///Vitae netus et, proin eros in.
        ///Delectus pede, aenean tellus.
        ///Dictum nibh.
        ///Turpis velit, elit porttitor vel.
        ///Feugiat nunc ultricies, ante maecenas, aliquet in.
        ///Fusce erat.
        ///Tincidunt vestibulum feugiat, neque pellentesque, vitae scelerisque.
        ///Cras fermentum, ut in vivamus.
        ///Mauris tempus.
        ///Purus risus.
        ///Sit eget, proin at iaculis, sed diam.
        ///Amet euismod vitae.
        ///Porta inter [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string loremIpsum {
            get {
                return ResourceManager.GetString("loremIpsum", resourceCulture);
            }
        }
    }
}
